#!/usr/bin/env node

var path = require('path');
var fs   = require('fs');
var lib  = path.join(path.dirname(fs.realpathSync(__filename)), '../lib/node_modules/coffee-script/lib');

require(lib + '/coffee-script/command').run();
